apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../base
- ns.yaml
- queue.yaml

images:
- name: europe-docker.pkg.dev/mediasaturn-demo/demo/demo-svc:1.0
  newTag: "2.0"

vars:
  - name: env
    objref:
      kind: Deployment
      name: demo-svc
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.namespace