apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems
  labels:
    app: ems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems
  template:
    metadata:
      labels:
        app: ems
    spec:
      containers:
      - name: ems
        image: europe-docker.pkg.dev/mediasaturn-demo/demo/ems:8.6
        ports:
        - containerPort: 7222
        volumeMounts:
        - name: ems-config
          mountPath: "/home/tibco"
          readOnly: true
      volumes:
      - name: ems-config
        configMap:
          name: ems-config
          items:
          - key: "queues.conf"
            path: "queues.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: ems
spec:
  selector:
    app: ems
  ports:
    - protocol: TCP
      port: 7222
      targetPort: 7222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-config
data:
  queues.conf: |
    queue.test.1