apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tibco-ems-operator
  name: tibco-ems-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tibco-ems-operator
  template:
    metadata:
      labels:
        app: tibco-ems-operator
    spec:
      serviceAccountName: tibco-ems-operator-account
      containers:
      - name: tibco-ems-operator
        image: europe-docker.pkg.dev/mediasaturn-demo/demo/tibco-ems-operator:57
        imagePullPolicy: Always
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "1000m"
        ports:
          - containerPort: 8080
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: kubernetes.default.svc.cluster.local
          - name: RUST_LOG
            value: tibco_ems=info,tibco_ems_operator=trace,info
          - name: STATUS_REFRESH_IN_MS
            value: "10000"
          - name: ENABLE_SCALING
            value: "TRUE"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_URL
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: serverUrl
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: tibco-ems-operator-secret
                key: password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tibco-ems-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tibco-ems-operator-role
rules:
- apiGroups: ["tibcoems.apimeister.com"]
  resources: ["queues","queues/status","topics","topics/status","bridges","bridges/status"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments","deployments/scale"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tibco-ems-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tibco-ems-operator-role
subjects:
- kind: ServiceAccount
  name: tibco-ems-operator-account
---
apiVersion: v1
kind: Secret
metadata:
  name: tibco-ems-operator-secret
type: Opaque
stringData:
  username: admin
  serverUrl: tcp://ems:7222
  password: admin
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bridges.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source_type:
                  type: string
                source_name:
                  type: string
                target_type:
                  type: string
                target_name:
                  type: string
                selector:
                  type: string
  scope: Namespaced
  names:
    plural: bridges
    singular: bridge
    kind: Bridge
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: queues.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                global:
                  type: boolean
                expiration:
                  type: integer
                  format: int32
                maxbytes:
                  type: integer
                  format: int64
                maxmsgs:
                  type: integer
                  format: int64
                maxRedelivery:
                  type: integer
                  format: int32
                overflowPolicy:
                  type: integer
                  format: int32
                prefetch:
                  type: integer
                  format: int32
                redeliveryDelay:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                pendingMessages:
                  type: integer
                  format: int64
                consumerCount:
                  type: integer
                  format: int32
      additionalPrinterColumns:
      - name: pending messages
        type: integer
        description: the number of pending messages
        jsonPath: .status.pendingMessages
      - name: consumer count
        type: integer
        description: the number of consumers
        jsonPath: .status.consumerCount
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: queues
    singular: queue
    kind: Queue
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topics.tibcoems.apimeister.com
spec:
  group: tibcoems.apimeister.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                expiration:
                  type: integer
                  format: int32
                name:
                  type: string
                global:
                  type: boolean
                maxbytes:
                  type: integer
                  format: int64
                maxmsgs:
                  type: integer
                  format: int64
                overflowPolicy:
                  type: integer
                  format: int32
                prefetch:
                  type: integer
                  format: int32
            status:
              type: object
              properties:
                pendingMessages:
                  type: integer
                  format: int64
                subscribers:
                  type: integer
                  format: int32
                durables:
                  type: integer
                  format: int32
      additionalPrinterColumns:
      - name: pending messages
        type: integer
        description: the number of pending messages
        jsonPath: .status.pendingMessages
      - name: subscriber count
        type: integer
        description: the number of subscribers
        jsonPath: .status.subscribers
      - name: durable count
        type: integer
        description: the number of durables
        jsonPath: .status.durables
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: topics
    singular: topic
    kind: Topic